#!/bin/bash

# iOS App Store Build Script for raaheHidayat
# Usage: ./build-ios-appstore.sh

set -euo pipefail

echo "🍎 Building raaheHidayat for App Store..."

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_TAURI_DIR="$ROOT_DIR/src-tauri"
APPLE_GEN_DIR="$SRC_TAURI_DIR/gen/apple"
WORKSPACE_PATH="$APPLE_GEN_DIR/raaheHidayat.xcodeproj/project.xcworkspace"
ARCHIVE_PATH="$ROOT_DIR/ipa_output/raaheHidayat.xcarchive"
EXPORT_PATH="$ROOT_DIR/ipa_output"
PRIMARY_EXPORT_OPTIONS="$ROOT_DIR/ExportOptions.plist"
FALLBACK_EXPORT_OPTIONS="$APPLE_GEN_DIR/exportOptionsAppStore.plist"

# Step 1: Build the Rust libraries if needed
echo "📦 Building Rust libraries..."
cd "$SRC_TAURI_DIR"

# Build for device (arm64) - required for App Store
# --features tauri/custom-protocol is REQUIRED here: without it Tauri compiles
# with dev=true and the app loads devUrl (http://localhost:3000) even in a
# Release/App Store build, instead of the bundled production assets.
cargo build --release --features tauri/custom-protocol --target aarch64-apple-ios --lib

# Create Externals directory if needed
mkdir -p gen/apple/Externals/arm64/release

# Copy the library with correct name
cp target/aarch64-apple-ios/release/libapp_lib.a gen/apple/Externals/arm64/release/libapp.a

echo "✅ Rust libraries ready"

cd ..

# Step 2: Run Tauri iOS build
echo "🔨 Running Tauri iOS build..."
npm run tauri ios build -- --target aarch64

# Step 3: Archive
echo "📦 Creating Xcode archive..."
mkdir -p "$EXPORT_PATH"
rm -rf "$ARCHIVE_PATH"

xcodebuild \
	-workspace "$WORKSPACE_PATH" \
	-scheme raaheHidayat_iOS \
	-configuration Release \
	-destination "generic/platform=iOS" \
	-archivePath "$ARCHIVE_PATH" \
	-allowProvisioningUpdates \
	archive

# Step 4: Export IPA
echo "📤 Exporting IPA..."

# Prefer the committed root ExportOptions.plist: gen/apple/ is regenerated by
# Tauri and its copy is not version-controlled, so it drifts.
EXPORT_OPTIONS_TO_USE="$PRIMARY_EXPORT_OPTIONS"
if [ ! -f "$EXPORT_OPTIONS_TO_USE" ]; then
	EXPORT_OPTIONS_TO_USE="$FALLBACK_EXPORT_OPTIONS"
fi

if [ ! -f "$EXPORT_OPTIONS_TO_USE" ]; then
	echo "❌ Could not find ExportOptions.plist"
	exit 1
fi
echo "   Using export options: $EXPORT_OPTIONS_TO_USE"

xcodebuild \
	-exportArchive \
	-archivePath "$ARCHIVE_PATH" \
	-exportPath "$EXPORT_PATH" \
	-exportOptionsPlist "$EXPORT_OPTIONS_TO_USE" \
	-allowProvisioningUpdates

# Step 5: Verify push entitlement survived signing
# The exported IPA is re-signed against a provisioning profile. If that profile
# has no aps-environment (e.g. it predates enabling Push Notifications on the
# App ID), codesign quietly drops the entitlement and the shipped app fails
# registerForRemoteNotifications() with "no valid aps-environment entitlement
# string found for application" — no token, no push, and nothing visible to the
# user beyond notifications never arriving. Fail the build here instead.
echo "🔎 Verifying aps-environment in exported IPA..."
IPA_PATH="$(ls -t "$EXPORT_PATH"/*.ipa 2>/dev/null | head -1)"
if [ -z "$IPA_PATH" ]; then
	echo "❌ No .ipa found in $EXPORT_PATH"
	exit 1
fi

VERIFY_DIR="$(mktemp -d)"
trap 'rm -rf "$VERIFY_DIR"' EXIT
unzip -q "$IPA_PATH" -d "$VERIFY_DIR"
VERIFY_APP="$(ls -d "$VERIFY_DIR"/Payload/*.app | head -1)"

APS_ENV="$(codesign -d --entitlements :- "$VERIFY_APP" 2>/dev/null \
	| plutil -extract aps-environment raw -o - - 2>/dev/null || true)"

if [ "$APS_ENV" != "production" ]; then
	echo ""
	echo "❌ Exported IPA has aps-environment='${APS_ENV:-<missing>}' (expected 'production')."
	echo "   Push notifications will NOT work in this build."
	echo ""
	echo "   Fix: in the Apple Developer portal enable the Push Notifications"
	echo "   capability on App ID com.prayer.raahe, then regenerate/redownload the"
	echo "   App Store provisioning profile so it carries aps-environment."
	echo "   Verify a profile is available with:"
	echo "     ./scripts/check-ios-push-profiles.sh"
	exit 1
fi
echo "✅ aps-environment=production"

echo ""
echo "✅ Build + archive + export complete!"
echo ""
echo "📦 Archive: $ARCHIVE_PATH"
echo "📱 Export folder: $EXPORT_PATH"
echo ""
ls -lh "$EXPORT_PATH" | sed 's/^/   /'
